import { StyleSheet } from 'react-native';
import type { ThemeColors } from '@/constants/tokens';

export function makeFilterBarStyles(C: ThemeColors) {
  return StyleSheet.create({
    bar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 6,
      backgroundColor: C.s1,
      borderBottomWidth: 1,
      borderBottomColor: C.b0,
    },
    filterBtn: {
      backgroundColor: C.s2,
      borderWidth: 1,
      borderColor: C.bw,
      borderRadius: 4,
      paddingHorizontal: 10,
      paddingVertical: 5,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    filterBtnActive: { borderColor: C.b2 },
    filterBtnText: {
      fontFamily: 'OverpassMono_600SemiBold',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      color: C.t3,
    },
    chip: {
      backgroundColor: C.amberBg,
      borderWidth: 1,
      borderColor: C.amberBorder,
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 4,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    chipText: { fontFamily: 'OverpassMono_500Medium', color: C.amber },
    chipClose: { fontFamily: 'OverpassMono_700Bold', color: C.t3 },
    clearBtn: { marginLeft: 'auto', paddingHorizontal: 8, paddingVertical: 4 },
    clearText: {
      fontFamily: 'OverpassMono_600SemiBold',
      color: C.t3,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    menuRow: {
      paddingVertical: 12,
      paddingHorizontal: 4,
      borderBottomWidth: 1,
      borderBottomColor: C.b0,
    },
    menuRowActive: { backgroundColor: C.amberBg },
    menuRowText: { fontFamily: 'NunitoSans_700Bold', color: C.t0 },
    menuRowTextActive: { color: C.amber },
    textInput: {
      fontFamily: 'NunitoSans_700Bold',
      color: C.t0,
      backgroundColor: C.s2,
      borderWidth: 1,
      borderColor: C.b0,
      borderRadius: 6,
      paddingHorizontal: 10,
      paddingVertical: 10,
      minHeight: 44,
    },
    applyBtn: {
      backgroundColor: C.amberBg,
      borderWidth: 1,
      borderColor: C.amber,
      borderRadius: 8,
      paddingVertical: 12,
      alignItems: 'center',
      marginTop: 16,
    },
    applyBtnDisabled: { opacity: 0.4 },
    applyText: {
      fontFamily: 'OverpassMono_700Bold',
      color: C.amber,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    opRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
    opPill: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: C.b1,
      backgroundColor: C.s2,
      alignItems: 'center',
    },
    opPillOn: { backgroundColor: C.amberBg, borderColor: C.amber },
    opPillText: {
      fontFamily: 'OverpassMono_600SemiBold',
      color: C.t3,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    opPillTextOn: { color: C.amber },
  });
}
